#!/bin/bash

### :: VARIABLES :: ###
USER=$1

### :: FUNCTIONS :: ###

## add required repos
function add_repos( )
	{
		wget -qO - https://regolith-desktop.org/regolith.key | gpg --dearmor | tee /usr/share/keyrings/regolith-archive-keyring.gpg > /dev/null
		
    echo deb "[arch=amd64 signed-by=/usr/share/keyrings/regolith-archive-keyring.gpg] https://regolith-desktop.org/release-ubuntu-jammy-amd64 jammy main" | tee /etc/apt/sources.list.d/regolith.list

		add-apt-repository -y ppa:papirus/papirus
    add-apt-repository -y ppa:diodon-team/stable
	}


## install zsh
function install_ZSH()
	{
		apt install -y zsh
		chsh -s /bin/zsh $USER
		wget -O /tmp/zsh_install.sh https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh
		chmod +x /tmp/zsh_install.sh
		su -c "/tmp/zsh_install.sh --unattended" - $USER
		rm /tmp/zsh_install.sh
	}


## install required packages
function install_packs( )
	{
		#install essentials
		apt install -y make git jq curl wget ffmpeg terminator pavucontrol mlocate

		#install i3 & plugins
		apt install -y i3-gaps i3blocks i3lock i3lock-fancy dunst suckless-tools rofi 

		#install features
		apt install -y feh fortune fonts-font-awesome fonts-jetbrains-mono papirus-folders papirus-icon-theme oxygen-cursor-theme oxygen-cursor-theme-extra nemo cowsay bluez bluez-tools blueman yad playerctl pulseaudio-utils xautolock redshift diodon
	}


## copy themes
function theme()
	{
		rsync -av --progress theme/* /usr/share/themes/
	}


## setup icons
function icon()
	{
		papirus-folders -C adwaita --theme Papirus-Dark
	}

	
## setup cursor
function cursor()
	{
		update-alternatives --set x-cursor-theme /etc/X11/cursors/oxy-terra.theme
	}


## copy fonts
function fonts()
	{
		mkdir -p /home/$USER/.local/share/fonts/customFonts
		rsync -av --progress --chown=$USER:$USER ./fonts/Montserrat /home/$USER/.local/share/fonts/customFonts/
		fc-cache -f -v
	}


## copy configuration files and them correleted settings
function copy_conf()
	{
		rsync -av --progress --chown=$USER:$USER .config/* /home/$USER/.config/
		rsync -av --progress --chown=$USER:$USER .zshrc .aliases /home/$USER/
		rsync -av --progress --chown=$USER:$USER zsh_themes/* /home/$USER/.oh-my-zsh/custom/themes
	}


## install extra tools
function extras()
	{
		#creation dir for locally bin files 
		mkdir -p /home/$USER/.local/bin
		LOCALBIN_PATH=/home/$USER/.local/bin
    GLOBBIN_PATH=/usr/bin
 
		# install micro editore
		curl https://getmic.ro | bash
		mv micro /usr/bin/

		# copy layouts handlers
		cp ./extras/openlayout ./extras/savelayout $GLOBBIN_PATH
		chmod 755 $GLOBBIN_PATH/openlayout
		chmod 755 $GLOBBIN_PATH/savelayout

		# copy wallpaper changer
		cp ./extras/feh_cw $LOCALBIN_PATH
		chown $USER:$USER $LOCALBIN_PATH/feh_cw
		chmod 755 $LOCALBIN_PATH/feh_cw
	
		# copy redlight script
		cp ./extras/redlight $LOCALBIN_PATH
		chown $USER:$USER $LOCALBIN_PATH/redlight
		chmod 755 $LOCALBIN_PATH/redlight				
	
		# copy hide cursor
		cp ./extras/unclutter $GLOBBIN_PATH/
    chmod 755 $LOCALBIN_PATH/unclutter

    # copy ufetch for terminal
    cp ./extras/ufetch $GLOBBIN_PATH/
    chmod 755 $LOCALBIN_PATH/ufetch
	}


## help message
function help()
	{
		echo "The script has to run as below:"
		echo -e "\t sudo /path/to/install <user>"
		echo "<user> must be replaced with the username who want install the environment"
	}


## done message
function finish()
	{
    RED='\033[0;31m'
    NC='\033[0m'
		clear
		echo -e "

${RED}WARNING: CHECK ALL CONFIGS AND SETTINGS BEFORE REBOOTING!!!${NC}
                                                                                
            dddddddd                                                            
            d::::::d                                                        !!! 
            d::::::d                                                       !!:!!
            d::::::d                                                       !:::!
            d:::::d                                                        !:::!
    ddddddddd:::::d    ooooooooooo   nnnn  nnnnnnnn        eeeeeeeeeeee    !:::!
  dd::::::::::::::d  oo:::::::::::oo n:::nn::::::::nn    ee::::::::::::ee  !:::!
 d::::::::::::::::d o:::::::::::::::on::::::::::::::nn  e::::::eeeee:::::ee!:::!
d:::::::ddddd:::::d o:::::ooooo:::::onn:::::::::::::::ne::::::e     e:::::e!:::!
d::::::d    d:::::d o::::o     o::::o  n:::::nnnn:::::ne:::::::eeeee::::::e!:::!
d:::::d     d:::::d o::::o     o::::o  n::::n    n::::ne:::::::::::::::::e !:::!
d:::::d     d:::::d o::::o     o::::o  n::::n    n::::ne::::::eeeeeeeeeee  !!:!!
d:::::d     d:::::d o::::o     o::::o  n::::n    n::::ne:::::::e            !!! 
d::::::ddddd::::::ddo:::::ooooo:::::o  n::::n    n::::ne::::::::e               
 d:::::::::::::::::do:::::::::::::::o  n::::n    n::::n e::::::::eeeeeeee   !!! 
  d:::::::::ddd::::d oo:::::::::::oo   n::::n    n::::n  ee:::::::::::::e  !!:!!
   ddddddddd   ddddd   ooooooooooo     nnnnnn    nnnnnn    eeeeeeeeeeeeee   !!! 
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
"
	}


function main()
  {
    apt update
		add_repos && apt update
		install_packs
		install_ZSH
		copy_conf
		theme
		icon
		cursor
		extras
		finish
  }

### :: MAIN :: ##

if [[ "$EUID" = 0 ]]; then
	if [[ $1 == "-h" ]]; then
		help
		exit 0
	else
    main
	fi
else
	echo -e "You must run the script with root privileges"
	echo -e "Lauch the script with -h option for help"
fi


