#!/bin/bash

old=$( cat $HOME/.config/gtk-3.0/settings.ini | grep "gtk-theme-name" | awk '{print $3}' )

looks=$( ls /usr/share/themes/ | grep "Flat-Remix-GTK" )

colors=$( echo "$looks" | awk -F'-' '{print $4,$5,$6}')

in=$(echo "$looks" | rofi -dmenu -p "GTK Themes" -config ~/.config/rofi/rofidmenu.rasi)

if [[ $in ]]; then
  sed -i "s/${old}/${in}/" $HOME/.config/gtk-3.0/settings.ini
fi

#cat $HOME/.config/gtk-3.0/settings.ini | grep "gtk-theme-name"
