#!/bin/bash


killall -q redshift > /dev/null


#while pgrep -x redshift > /dev/null; do sleep 1; done

if [[ -f /tmp/tmp.rs ]]; then
	b=$(cat /tmp/tmp.rs)
else
	b=70
fi


if [[ $1 == "up" && $b -lt 100 ]]; then
	((b+=10))
elif [[ $1 == "down" && $b -gt 10 ]]; then
	((b-=10))
elif [[ $1 == "lamadonnaputtana" ]]; then
	b=100
fi 

echo $b > /tmp/tmp.rs

b=$(awk "BEGIN { print $b/100 }")

redshift -P -b $b -r &
