#!/bin/bash
LPATH=/home/$USER/.config/i3/layouts
WS=$1
TYPE=$2

if [[ $# -lt 1 || $# -ge 3 ]]; then
	echo -e "Illegal arguments"
	echo -e "Run $0 -h to print help"
elif [[ $# -eq 1 && $1 == '-h' ]]; then
	echo -e "To open a specific layout run\n\n   $0 <workspace> <layout>\n"
	echo -e "<workspace> is the workspace number from which to get layout rules"
	echo -e "<layout> is the name of the json file where the layout rules are saved"
else
	i3-save-tree --workspace=$WS > $LPATH/$TYPE.json
fi

sed -i '1d' $LPATH/$TYPE.json # remove 1st row
grep -Ev '// \b[a-z]' $LPATH/$TYPE.json > $LPATH/$TYPE.tmp.json # remove comments from json
mv $LPATH/$TYPE.tmp.json $LPATH/$TYPE.json 
sed -i 's/\///g' $LPATH/$TYPE.json # uncomment json rules
grep -Ev '"title"|"machine"|"window_role"' $LPATH/$TYPE.json > $LPATH/$TYPE.tmp.json # remove useless swallows 
mv $LPATH/$TYPE.tmp.json $LPATH/$TYPE.json 
sed -i '/^ *\}/{H;x;s/\([^}]\),\n/\1\n/;b};x;/^ *}/d' $LPATH/$TYPE.json # remove last commas from json